### ISSUE TITLE
xxx is undefined issue in jQuery

### ISSUE THREAD

**Issue by jmav** [binaryage/firequery#27] opened 2012-01-27 12:16 UTC
Environment:
Win 7 64bit
FF 9.0.1 Eng.
Firequery 1.1

test web address:
http://jqueryui.com/demos/draggable/

When moving div in sample, following errors appears:
a(this).data("draggable") is undefined

Similar issues appears also in:
http://layout.jquery-dev.net/demos/complex.html

**Comment by darwin** [comment] 2012-04-17 17:57
dupe of issue #28

**Closed as completed by darwin** 2012-04-17 17:57 UTC
