### ISSUE TITLE
Firebug 2.0 stopped showing internal data for all jQuery versions

### ISSUE THREAD

**Issue by pocesar** [binaryage/firequery#39] opened 2014-06-11 21:31 UTC
Firebug 2.0 stopped showing internal data for all jQuery versions, tested with 1.11 and 2.1.1, in the HTML tab.

**Comment by tobigit** [comment] 2014-06-23 12:48
FireQuery stopped working also in my browser. No DOM-Bindings are shown anymore.

Firefox: 30.0
Firebug: 2.0.1
FireQuery: 1.4.1

**Comment by atwright147** [comment] 2014-06-25 10:23
I believe this is a duplicate of issue #34

**Comment by tobigit** [comment] 2014-06-25 11:06
No, the jQuery version is not the problem. We are using jQuery 1.10.2 which works fine with Firequery 1.41. a long time.

I did a downgrade of Firebug to 1.12.8 yesterday and now FireQuery works fine again. DOM-bindings are shown correctly!

FireQuery stopps working with Firebug 2.x

**Comment by darwin** [comment] 2014-06-25 11:22
I assume format of tree-view in Firebug changed. I didn't have time to really install Firebug 2.0 and test my extensions there.

I'm still planning on doing that, but it does not have that big priority for me. Haven't been doing any serious webdev for a while.

**Comment by KODerFunk** [comment] 2014-07-16 13:23
Fix it please.

**Comment by 5im-0n** [comment] 2014-08-01 13:12
:thumbsup:

**Comment by pocesar** [comment] 2014-08-15 17:43
it broke angular + ui-router + jquery 2.1.1 on page, this lack of support is dangerous. 
angular-ui/ui-router#1104

**Comment by mhulse** [comment] 2014-08-16 20:58
> I'm still planning on doing that, but it does not have that big priority for me. Haven't been doing any serious webdev for a while.

This was a really useful plugin for jquery dev. Anyone out there able to help @darwin with a PR on this issue?

**Comment by darwin** [comment] 2014-08-17 19:18
Hi again,

I think it is the time to face sad truth and call FireQuery unsupported software from my side. 

The problem is that I don't have motivation to spend time on maintaining it. I hate broken software, but I have other projects which pay my bills and require constant maintenance (TotalFinder, TotalTerminal, etc.). I don't do heavy jQuery development anymore. And for my current web development tasks I switched completely to Chrome+Web Inspector.

Anyone want to step up and take this project?

**Comment by mhulse** [comment] 2014-08-17 20:36
@darwin Totally understandable. I completely sympathize. I wish I knew enough to take this over, or, at least help maintain.

Dumb question: What's the main programming language used to create the FireQuery plugin?

Speaking of Chrome, are there tools, in that browser, that do the same job as FireQuery?

**Comment by darwin** [comment] 2014-08-17 20:40
Firefox addons are written in javascript. FireQuery is quite ugly and convoluted piece of code:
https://github.com/binaryage/firequery/blob/master/firefox/chrome/content/firequery.js

I don't know about anything similar for Chrome.

**Comment by mhulse** [comment] 2014-08-17 20:44
> Firefox addons are written in javascript. FireQuery is quite ugly and convoluted piece of code:
> https://github.com/binaryage/firequery/blob/master/firefox/chrome/content/firequery.js

Interesting! I'll take a closer look. :+1: 

I wonder what changed in Firebug that broke FireQuery? Part of me wonders if there's a simple fix.

What do you use to debug when developing a plugin? Might be interesting to turn on debug to see where/why Firequery isn't working. There's got to be some sort of API change that may (or may not be) easy to fix?

Anyway, thanks for the replies @darwin, much appreciated.

**Comment by darwin** [comment] 2014-08-17 20:56
I don't know what broke it. FireQuery has to adapt three moving parts: jQuery internals, Firefox addons system and Firebug code. All three interfaces have been evolving over last 5 years. My bet is that this time something broke because of jQuery re-implementation of some internal $.data related code or Firebug changed the way how to render HTML panel.

For debugging I used debug prints, because good debuggers were not available for Mozilla platform at the time. Even setting up an add-ons development environment is quite challenging. Maybe things improved from last year - I saw quite active development of Firefox itself. You should find relevant docs here:
https://developer.mozilla.org/en-US/Add-ons

my $.02

**Comment by mhulse** [comment] 2014-08-17 21:19
Interesting! Thanks for the feedback/link @darwin. If I find the free time I may look into this (though, I can totally relate to your time/money/pay the bills statement/sentiment).

**Comment by beam2web** [comment] 2014-09-19 22:07
With attr() it seems to work partially, but for objects I'm not sure if that was possible in the past

```
var $input = $('#input'); // original <input id="input" type="text" />

$input
    .data('first', 'true')
    .data('second', {foo: 16, bar: "something"})
    .attr('data-third', 'true')
    .attr('data-fourth', {first: 16, last: "this is the last"});

// output <input id="input" type="text" data-third="true" data-fourth="[object Object]">
```

tested with: Firefox 32.0.2, Firebug 2.0.4, FireQuery 1.4.1, jQuery 1.10.2

**Comment by tobigit** [comment] 2014-10-16 07:59
Has anybody a solution meanwhile? This plugin is very important for me.
Or has anybody a hint for me how i can debug this extension?

**Comment by tobigit** [comment] 2014-11-10 08:49
Hi kbaniszack!
With your solution the DOM-bindings are shown only on the DOM-Element "html" under firebug 2.0.6. This is a good news so far. The Plugin works under firebug 2.x
Maybe it is only a trifle to get the rest working?! ;-)

**Comment by ms-berry** [comment] 2015-01-06 12:54
it seems to be problem with apply() function in jQuery.__FireQueryShared.removeData_originalReplacedByFireQuery 
jQuery.__FireQueryShared.data_originalReplacedByFireQuery
i quickfix this and seems to work now, dont have time for more investigation at the moment:)
full /chorome/content/firequery.js here:
http://pastebin.com/N6gArmyP

**Comment by FlashJunior** [comment] 2015-01-14 12:36
Any update?

**Comment by FlashJunior** [comment] 2015-02-27 06:36
Any plans to fix this?

**Comment by darwin** [comment] 2015-02-27 08:08
No immediate plans for update. I don't use Firefox&Firebug for my web development. Also I don't use jQuery anymore.

Sorry guys. You have to downgrade or fix it yourself.

**Comment by janodvarko** [comment] 2015-03-17 13:57
New version of FireQuery (beta 1) is available.

New FireQuery 2 is (re)built on top of native developer tools and is compatible with Firefox 36-39. FireQuery 2 doesn't require Firebug, but is nicely integrated with Firebug 3 (aka Firebug.next) that is also built on top of Firefox native developer tools.

FireQuery 2 new home page:
https://github.com/firebug/firequery/wiki

FireQuery 2 new issue list: 
https://github.com/firebug/firequery/issues

FireQuery 2 is in beta phase now and we'd love to hear some feedback from you before we do the final release, thanks!

Honza

**Comment by FlashJunior** [comment] 2015-03-17 14:17
@janodvarko great news! thx a lot!

**Closed as completed** 2017-09-19 08:35 UTC
